# ./.build/velopack.yml
version: "3"

tasks:
  pack:
    vars:
      OS: "{{.OS}}"
      ARCH: "{{.ARCH }}"
      RID: "{{.OS}}-{{.ARCH}}"
      PUBLISH_DIR: "{{.OUTPUT_DIR}}/publish/{{.RID}}"
      RELEASES_DIR: "{{.OUTPUT_DIR}}/releases/{{.RID}}"
    desc: "Packages the published application using Velopack"
    preconditions:
      - sh: |
          {{if eq .OS "windows"}}
            powershell -Command "exit !(Test-Path '{{.ICON_PATH}}' -PathType Leaf)"
          {{else}}
            [ -f '{{.ICON_PATH}}' ]
          {{end}}
        msg: "Velopack icon not found at '{{.ICON_PATH}}'. Check ICON_PATH in .env."
    cmds:
      - echo "Packing application for {{.OS}}/{{.ARCH}}"
      - |
        vpk [{{.OS}}] pack \
          --packId {{.APP_NAME}} \
          --packVersion {{.APP_VERSION}} \
          --packDir "{{.PUBLISH_DIR}}" \
          --mainExe {{if eq .OS "win"}}{{.APP_NAME}}.exe{{else}}{{.APP_NAME}}{{end}} \
          --packAuthors "{{.COMPANY_NAME}}" \
          --packTitle "{{.APP_NAME}}" \
          --outputDir "{{.RELEASES_DIR}}" \
          --runtime {{.RID}} \
          --icon "{{.ICON_PATH}}"
