// This file is generated by cslox.tool. Do not edit it manually.
namespace cslox;

public abstract record Expr
{
    public interface IVisitor<T>
    {
        public abstract T Visit(Binary expr);
        public abstract T Visit(Grouping expr);
        public abstract T Visit(Literal expr);
        public abstract T Visit(Unary expr);
    }

    public record Binary(Expr left, Token opr, Expr right) : Expr
    {
        public override T Accept<T>(IVisitor<T> visitor)
        {
            return visitor.Visit(this);
        }
    }

    public record Grouping(Expr expression) : Expr
    {
        public override T Accept<T>(IVisitor<T> visitor)
        {
            return visitor.Visit(this);
        }
    }

    public record Literal(object value) : Expr
    {
        public override T Accept<T>(IVisitor<T> visitor)
        {
            return visitor.Visit(this);
        }
    }

    public record Unary(Token opr, Expr right) : Expr
    {
        public override T Accept<T>(IVisitor<T> visitor)
        {
            return visitor.Visit(this);
        }
    }

    public abstract T Accept<T>(IVisitor<T> visitor);
}
