// This file is generated by cslox.tool. Do not edit it manually.
namespace cslox;

record Expr
{
    record Binary(Expr left, Token opr, Expr right) : Expr;

    record Grouping(Expr expression) : Expr;

    record Literal(object value) : Expr;

    record Unary(Token opr, Expr right) : Expr;
}
