# ./.build/dotnet.yml
version: "3"

vars:
  SOLUTION_FILE: "{{.SOLUTION_FILE}}"
  CONFIGURATION: '{{.CONFIGURATION | default "Release"}}'
  OUTPUT_DIR: '{{.OUTPUT_DIR | default "dist"}}'
  NUGET_OUTPUT_DIR: "{{.OUTPUT_DIR}}/nuget"

tasks:
  # ... (clean, restore, build, test are unchanged) ...
  clean:
    desc: "Runs 'dotnet clean' on the solution"
    cmds:
      - dotnet clean "{{.SOLUTION_FILE}}"

  restore:
    desc: "Restores NuGet packages for the solution"
    cmds:
      - dotnet restore "{{.SOLUTION_FILE}}"

  build:
    desc: "Builds the solution in {{.CONFIGURATION}} configuration"
    deps: [restore]
    cmds:
      - dotnet build "{{.SOLUTION_FILE}}" -c {{.CONFIGURATION}} --no-restore

  test:
    desc: "Runs all tests in the solution"
    deps: [build]
    cmds:
      - dotnet test "{{.SOLUTION_FILE}}" -c {{.CONFIGURATION}} --no-build -tl:off

  lint:
    desc: "Runs the linter on the solution"
    cmds:
      - dotnet csharpier check .
  format:
    desc: "Formats the codebase using CSharpier"
    cmds:
      - dotnet csharpier format .

  # This task is specifically for publishing a runnable application's files
  publish-app:
    desc: "Publishes a runnable application to a directory"
    deps: [clean]
    vars:
      PROJECT_TO_PUBLISH: "{{.PROJECT_TO_PUBLISH}}"
      OS: "{{.OS}}"
      ARCH: "{{.ARCH}}"
      RID: "{{.OS}}-{{.ARCH}}"
      PUBLISH_DIR: "{{.OUTPUT_DIR}}/publish/{{.RID}}"
    cmds:
      - echo "Publishing {{.PROJECT_TO_PUBLISH}} for {{.OS}}/{{.ARCH}} to {{.PUBLISH_DIR}}"
      - dotnet publish "src/{{.PROJECT_TO_PUBLISH}}" -c {{.CONFIGURATION}} -r {{.RID}} -o "{{.PUBLISH_DIR}}"
    preconditions:
      - '{{ ne .OS "" }}'
      - '{{ ne .ARCH "" }}'
      - '{{ ne .PROJECT_TO_PUBLISH "" }}'

  # This task is specifically for creating a NuGet package from a library
  pack-nuget:
    desc: "Packs the project as a NuGet package"
    vars:
      PROJECT_TO_PACK: "{{.PROJECT_TO_PACK}}"
    cmds:
      - dotnet pack "src/{{.PROJECT_TO_PACK}}" -c {{.CONFIGURATION}} --no-build -o {{.NUGET_OUTPUT_DIR}}

  push-nuget:
    desc: "Pushes the NuGet package to a feed"
    dir: "{{.NUGET_OUTPUT_DIR}}"
    # This task requires these variables to be set in the environment
    preconditions:
      - '{{ ne .NUGET_SOURCE_URL "" }}'
      - msg: "NUGET_SOURCE_URL is not set in your .env/public.env file."
    cmds:
      - >
        dotnet nuget push "*.nupkg"
        -k {{.NUGET_API_KEY}}
        -s {{.NUGET_SOURCE_URL}}
        --skip-duplicate
